#! /bin/sh

feh --bg-scale ~/Images/macg.jpg &

bspc rule -a Code border=off

xrandr --output DP-4 --mode 3440x1440 --rate 99.98



# Run EWW.
eww -c $HOME/.config/eww --restart open barra &

picom --config ~/.config/picom/picom.conf &

pgrep -x sxhkd > /dev/null || sxhkd &

#Google Drive
rclone mount gdrive:/ /home/kelly/"Google Drive" --vfs-cache-mode writes &

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Discord desktop='^8' state=floating follow=on
bspc rule -a Spotify desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off






#focus al pasar raton
bspc config focus_follows_pointer true


#Establece curson left por defecto
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources


